# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 580d6d192698e03bdbcea608641b005b9946b29bbe831d3bb904a415adb41400a2345e20cffdb8330416edf277ac4afa21d8cc7028c3a28c502450ff5936ff7d

test:
  secret_key_base: f92c54e154504d6f9bbc23699bdf9b5c1527f7eb41fe940ef991a824c221f27eb0cb64d96feba6933e8d4f07c41e1be591ff7148a9555d76edabb673d9e99215

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
